# Parse "Rung Trăng Vàng 500 câu" text dump (rcv_raw.txt, from the PDF via pypdf) into src/quiz.js
import re, json, sys
raw = open('rcv_raw.txt', encoding='utf-8').read()
lines = [l.rstrip() for l in raw.split('\n')]
topics, cur_topic = [], None
items = []
nums = []
expect = 1
pending = None
i = 0
state = None  # None | 'q' | 'a'
q, a = [], []
def flush():
    global q, a
    if q and a:
        items.append({'t': cur_topic, 'q': ' '.join(q).strip(), 'a': ' '.join(a).strip()})
    q, a = [], []
for l in lines:
    s = l.strip()
    if not s or s.startswith('Rung Trăng Vàng 2026'): continue
    m = re.match(r'^CHỦ ĐỀ (\d+):\s*(.+)$', s)
    if m:
        flush(); state = None
        cur_topic = int(m.group(1)) - 1
        while len(topics) <= cur_topic: topics.append(m.group(2).strip().title())
        continue
    if cur_topic is None: continue
    mnum = re.match(r'^(\d{1,3})$', s)  # question number: must be the next one in sequence
    if mnum:
        if int(s) == expect:
            flush(); state = 'q'; nums.append(expect); expect += 1; continue
        if pending is not None and int(pending + s) == expect:
            flush(); state = 'q'; nums.append(expect); expect += 1; pending = None; continue
        pending = s; continue
    pending = None
    if state == 'q':
        q.append(s)
        if s.endswith('?') or s.endswith(':'): state = 'a'
    elif state == 'a':
        a.append(s)
flush()
print('topics', len(topics), 'items', len(items), file=sys.stderr)
# sanity: questions without '?' end
bad = [x for x in items if not (x['q'].endswith('?') or x['q'].endswith(':'))]
print('no-? questions', len(bad), file=sys.stderr)
for x in bad[:8]: print('  ', x, file=sys.stderr)
for k in range(5): print('topic', k, sum(1 for x in items if x['t'] == k), file=sys.stderr)
js = "// Generated by src/mkquiz.py from the family's own 'Rung Trăng Vàng 2026' revision set. Do not edit by hand.\nconst QUIZ_TOPICS = " + json.dumps(topics, ensure_ascii=False) + ";\nconst QUIZ = " + json.dumps(items, ensure_ascii=False, separators=(',', ':')) + ";\n"
open('src/quiz.js', 'w', encoding='utf-8', newline='\n').write(js)
odd=[x for x in items if len(x['a'])<2 or len(x['q'])<8]
print('odd',odd[:5], file=sys.stderr)
print('wrote src/quiz.js', len(js), file=sys.stderr)
